pipeline {
    agent {
        docker {
            image 'maven:3.9.4-eclipse-temurin-17'
            args '-v /root/.m2:/root/.m2'   // cache Maven repo
        }
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'First_JenkinsProj_Java',
                    url: 'https://github.com/girishpote19/Jenkins-Projects.git'
            }
        }

        stage('Test') {
            steps {
                dir('demo') {   // navigate to folder where pom.xml is
                    sh 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('demo') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Deploy (practice)') {
            steps {
                echo "✅ Build successful! Next step: Dockerize and deploy."
            }
        }
    }
}
