pipeline {
        agent {
                docker {
                        image 'maven:3.9.4-eclipse-temurin-17'
                        args '-v /root/.mr:/root/.m2'
                        }
                }

                stages {
                        stage('Checkout') {
                                steps {
                                        git branch: 'First_JenkinsProj_Java/demo', url: 'https://github.com/girishpote19/Jenkins-Projects.git'

                                        }
                                }
                        stage('Test') {
                                steps {
                                        sh 'mvn test'
                                        }
                                }
                        stage('Package') {
                                steps {
                                        sh 'mvn package -DskipTestes'
                                        }
                                }
                        stage('Archive Artifact') {
                                steps {
                                        archiveArtifacts artifacts: 'target/*.war', fingerprint: true
                                        }
                                }
                        stage('Deploy (practice)') {
                                steps {
                                        echo " I am able to deploy now will Dockerize it in Future"
                                        }
                                }
                        }
                }
